//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewspaperAds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allocation
    {
        public int ID { get; set; }
        public int IssueID { get; set; }
        public int AdID { get; set; }
    
        public virtual Ad Ad { get; set; }
        public virtual Issue Issue { get; set; }
    }
}
